# Generated by Django 4.2.6 on 2023-12-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipie_image',
            new_name='receipe_image',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='receipie_name',
            new_name='receipe_name',
        ),
    ]
